SPK_NAME = rdfind
SPK_VERS = 1.5
SPK_REV = 0
SPK_ICON = src/rdfind.png

DEPENDS  = cross/$(SPK_NAME)

MAINTAINER = drodbar
DESCRIPTION = "Rdfind is a command line tool that finds duplicate files"
DISPLAY_NAME = Rdfind
CHANGELOG =
STARTABLE = no

HOMEPAGE = https://github.com/pauldreik/rdfind
LICENSE = GPLv2

SPK_COMMANDS = bin/rdfind

include ../../mk/spksrc.spk.mk

