SPK_NAME = neovim
SPK_VERS = 0.7.2
SPK_REV = 0
SPK_ICON = src/neovim.png

DEPENDS  = cross/$(SPK_NAME)

MAINTAINER = drodbar
DESCRIPTION = "hyperextensible Vim-based text editor"
DISPLAY_NAME = Neovim
CHANGELOG =
STARTABLE = no

HOMEPAGE = https://neovim.io/
LICENSE = GPLv2

SPK_COMMANDS = bin/nvim

include ../../mk/spksrc.spk.mk

